apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-ecoflow-exporter.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "go-ecoflow-exporter.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "go-ecoflow-exporter.name" . }}
    spec:
      containers:
        - name: exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: metrics
              containerPort: 2112
              protocol: TCP

          env:
            # --- common ---
            - name: PROMETHEUS_ENABLED
              value: {{ .Values.prometheus.enabled | quote }}

            - name: EXPORTER_TYPE
              value: {{ .Values.exporter.type | quote }}

            {{- if .Values.exporter.devices }}
            - name: ECOFLOW_DEVICES
              value: {{ .Values.exporter.devices | quote }}
            {{- end }}

            {{- if .Values.exporter.devicesPrettyNames }}
            - name: ECOFLOW_DEVICES_PRETTY_NAMES
              value: {{ .Values.exporter.devicesPrettyNames | quote }}
            {{- end }}

            - name: MQTT_DEVICE_OFFLINE_THRESHOLD_SECONDS
              value: {{ .Values.exporter.mqtt.deviceOfflineThresholdSeconds | quote }}

            # --- REST MODE ---
            {{- if eq .Values.exporter.type "rest" }}
            - name: ECOFLOW_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: ECOFLOW_ACCESS_KEY

            - name: ECOFLOW_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: ECOFLOW_SECRET_KEY
            {{- end }}

            # --- MQTT MODE ---
            {{- if eq .Values.exporter.type "mqtt" }}
            - name: ECOFLOW_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: ECOFLOW_EMAIL

            - name: ECOFLOW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: ECOFLOW_PASSWORD
            {{- end }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
