{{- include "go-ecoflow-exporter.validate" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-ecoflow-exporter.fullname" . }}
  labels:
    app: {{ include "go-ecoflow-exporter.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "go-ecoflow-exporter.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "go-ecoflow-exporter.name" . }}
    spec:
      containers:
        - name: exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: metrics
              containerPort: 2112
              protocol: TCP

          env:
            # ------------------
            # Common
            # ------------------
            - name: PROMETHEUS_ENABLED
              value: {{ .Values.prometheus.enabled | quote }}

            - name: EXPORTER_TYPE
              value: {{ .Values.exporter.type | quote }}

            - name: MQTT_DEVICE_OFFLINE_THRESHOLD_SECONDS
              value: {{ .Values.exporter.mqtt.deviceOfflineThresholdSeconds | quote }}

            - name: DEBUG
              value: {{ .Values.debug.enabled | quote }}

            # ------------------
            # REST credentials
            # ------------------
            {{- if eq .Values.exporter.type "rest" }}
            - name: ECOFLOW_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: ECOFLOW_ACCESS_KEY

            - name: ECOFLOW_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: ECOFLOW_SECRET_KEY
            {{- end }}

            # ------------------
            # MQTT credentials + devices
            # ------------------
            {{- if eq .Values.exporter.type "mqtt" }}
            - name: ECOFLOW_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: ECOFLOW_EMAIL

            - name: ECOFLOW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: ECOFLOW_PASSWORD

            - name: ECOFLOW_DEVICES
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: ECOFLOW_DEVICES
                  optional: true

            - name: ECOFLOW_DEVICES_PRETTY_NAMES
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: ECOFLOW_DEVICES_PRETTY_NAMES
                  optional: true
            {{- end }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
