apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-ecoflow-exporter.fullname" . }}
type: Opaque
stringData:
  ECOFLOW_ACCESS_KEY: {{ .Values.credentials.accessKey | quote }}
  ECOFLOW_SECRET_KEY: {{ .Values.credentials.secretKey | quote }}
  ECOFLOW_EMAIL: {{ .Values.credentials.email | quote }}
  ECOFLOW_PASSWORD: {{ .Values.credentials.password | quote }}
