{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "go-ecoflow-exporter.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "go-ecoflow-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "go-ecoflow-exporter.chart" . }}
{{- end }}
