apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-ecoflow-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "go-ecoflow-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "go-ecoflow-exporter.chart" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2112
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "go-ecoflow-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
