apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-ecoflow-exporter.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2112
      protocol: TCP
      name: http
  selector:
    app: {{ include "go-ecoflow-exporter.name" . }}
