apiVersion: v2
appVersion: 2.2.0.0
description: A Helm chart for duplicati
home: https://github.com/dev-shynkar/HelmCharts/tree/master/duplicati
icon: https://raw.githubusercontent.com/dev-shynkar/HelmCharts/master/Duplicati/images/duplicati-logo.png
name: duplicati
sources:
- https://hub.docker.com/r/linuxserver/transmission
type: application
version: 0.11.0
