{{- if .Values.configPersistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "samba.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "samba.name" . }}
    helm.sh/chart: {{ include "samba.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.configPersistence.size | default "100Mi" }}
  {{- if .Values.configPersistence.storageClass }}
  storageClassName: {{ .Values.configPersistence.storageClass }}
  {{- end }}
{{- end }}
