replicaCount: 1

image:
  repository: tess1o/go-ecoflow-exporter
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 2112

exporter:
  type: mqtt        # mqtt | rest

  devices: ""
  devicesPrettyNames: ""

  mqtt:
    deviceOfflineThresholdSeconds: 30

existingSecret:
  enabled: true
  name: go-ecoflow-exporter

prometheus:
  enabled: true

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
