apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "transmission.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9091
      protocol: TCP
      name: http
